tabname: pull_req
on:
  pull_request:
    branches:
      ["main"]
jobs:
 esc build:
    runs-on: ubuntu-latest
    tabsteps:
    - uses: actions/checkout@v2
    - run: ./bin/detect
    - run: ./bin/compile $PWD
    - run: ./bin/release
